CPP=		g++ $(CCFLAGS)
HEAP=		heap-overflow.cc
HEAP2=		heap-overflow2.cc

OBJS =		$(HEAP) $(HEAP2)

LIBS=		-fno-stack-protector -no-pie

CCFLAGS= -g -m32


 
all: heap heap2

heap:	$(HEAP)
		$(CXX) $(CCFLAGS) -fno-stack-protector -no-pie $^ -o $@

heap2:	$(HEAP2)
		$(CXX) $(CCFLAGS) -fno-stack-protector -no-pie $^ -o $@

clean:
		rm -f *.o


